kind: Deployment
apiVersion: apps/v1
metadata:
# set your lab user name
  name: {{ .Release.Name }}-1
  annotations:
   argocd.argoproj.io/sync-wave: 5
spec:
  replicas: {{ .Values.ReplicaNumber }}
  selector:
    matchLabels: 
# set your lab user name
      app1: {{ .Release.Name }}-1
  template:
    metadata:
      Annotations:
        checksum/config: {{ include (print $.Template.BasePath "/ConfigMap.yaml") . | sha256sum }}
      labels:
# set your lab user name
        app1: {{ .Release.Name }}-1
    spec:
      volumes:
        - name: index-html
          configMap:
            name: index.html
            defaultMode: 420
      containers:
        - resources: {}
          volumeMounts:
          - name: index-html
            mountPath: {{ .Values.volume.mount.path }} # this will mount the html.index file to it application location
          readinessProbe:
{{- tpl (toYaml .Values.probes.readiness) . | nindent 12 }}
          livenessProbe:
{{- tpl (toYaml .Values.probes.liveness) . | nindent 12 }}
          env:
            - name: PORT
              value: {{ .Values.containers.containerPort | quote }}
          terminationMessagePath: /dev/termination-log
          name: {{ .Release.Name }}-1
          ports:
            - containerPort: {{ .Values.containers.containerPort }}
              protocol: TCP
          imagePullPolicy: IfNotPresent
# update with the image you build in part 1
          image: {{ .Values.containers.image }}:{{ .Values.containers.tag }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10