ReplicaNumber: 1

containers:
  containerPort: 8080
  image: 'quay.io/idopin/myrepo'
  tag: 'chart_v1'

service:
  servicePort: 8080

probes:
  readiness:
    httpGet:
      path: /health/readiness 
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 1 
    timeoutSeconds: 1 
    periodSeconds: 10 
    successThreshold: 1 
    failureThreshold: 3 
  liveness:
    httpGet:
      path: /health/liveliness
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3

volume:
  mount:
    path: /tmp/html

test: Healthy
# test: Null

github:
  user: IdoPin # Your GitHub User name
  token: empty-pass
  url: https://api.github.com/repos/IdoPin/app-dev-lab/issues